namespace SttpMcp.Storage.SurrealDb.Models;

public sealed record SurrealNodeRecord(
    string SessionId,
    string Raw,
    string Tier,
    DateTime Timestamp,
    int CompressionDepth,
    string? ParentNodeId,
    double Psi,
    double Rho,
    double Kappa,
    double UserStability,
    double UserFriction,
    double UserLogic,
    double UserAutonomy,
    double UserPsi,
    double ModelStability,
    double ModelFriction,
    double ModelLogic,
    double ModelAutonomy,
    double ModelPsi,
    double CompStability,
    double CompFriction,
    double CompLogic,
    double CompAutonomy,
    double CompPsi,
    double ResonanceDelta);
