{
 "title": "Codebase Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Current Average Health",
   "type": "gauge",
   "description": "Displays the average health for the project as saved in surrealdb",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "mode": "raw",
     "rateFunctions": [ "count" ],
     "surql": "        SELECT \n            count() as TotalNodes,\n            math::mean(avec_stability) as Stability,\n            math::mean(avec_logic) as Logic,\n            math::mean(avec_friction) as Friction,\n            math::mean(avec_autonomy) as Autonomy\n        FROM node\n        WHERE avec_stability IS NOT NONE\n        GROUP ALL;"
    }
   ]
  },
  {
   "title": "Live Stability",
   "type": "gauge",
   "description": "Overall Stability measurement of codebase",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "median" ] } },
   "targets": [
    {
     "filters": [
      {
       "id": "0426554e",
       "isCustomValue": true,
       "operator": "<",
       "scope": "span",
       "tag": "avec.stability",
       "value": [ "0.7" ],
       "valueType": "float"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ .avec.stability > 0.1}",
     "spss": 50,
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Live Friction",
   "type": "gauge",
   "description": "Overall friction measurement of codebase",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "median" ] } },
   "targets": [
    {
     "filters": [
      {
       "id": "0426554e",
       "isCustomValue": true,
       "operator": "<",
       "scope": "span",
       "tag": "avec.stability",
       "value": [ "0.7" ],
       "valueType": "float"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ .avec.friction > 0.1}",
     "spss": 50,
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Codebase Complexity",
   "type": "heatmap",
   "description": "Cyclomatic complexity per function",
   "gridPos": { "h": 23, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(codebase_complexity_bucket{ }[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Live Autonomy",
   "type": "gauge",
   "description": "Overall Autonomy measurement of codebase",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "median" ] } },
   "targets": [
    {
     "filters": [
      {
       "id": "0426554e",
       "isCustomValue": true,
       "operator": "<",
       "scope": "span",
       "tag": "avec.stability",
       "value": [ "0.7" ],
       "valueType": "float"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ .avec.autonomy > 0.1}",
     "spss": 50,
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Live Logic",
   "type": "gauge",
   "description": "Overall Logic measurement of codebase",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "median" ] } },
   "targets": [
    {
     "filters": [
      {
       "id": "0426554e",
       "isCustomValue": true,
       "operator": "<",
       "scope": "span",
       "tag": "avec.logic",
       "value": [ "0.6" ],
       "valueType": "float"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "spss": 50,
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Test Debt",
   "type": "xychart",
   "description": "Top 20 Functions with highest cyclomatic complexity",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "mode": "raw",
     "rateFunctions": [ "count" ],
     "surql": "SELECT \n    name,\n    cyclomatic_complexity,\n    lines_of_code,\n    avec_friction\nFROM node\nWHERE cyclomatic_complexity > 10\nORDER BY cyclomatic_complexity DESC\nLIMIT 20;"
    }
   ]
  },
  {
   "title": "Commit History",
   "type": "histogram",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 10 },
   "targets": [
    {
     "filters": [
      {
       "id": "0426554e",
       "isCustomValue": true,
       "operator": "<",
       "scope": "span",
       "tag": "avec.stability",
       "value": [ "0.7" ],
       "valueType": "float"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ .history.commits.recent > 0 }",
     "spss": 50,
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Danger Zone",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 15 },
   "targets": [
    {
     "mode": "raw",
     "rateFunctions": [ "count" ],
     "surql": "SELECT \n    name AS Function,\narray::last(string::split(file_path, \"/\")) as FileName,\n    git_total_commits AS TotalCommits,\n    avec_stability AS Stability,\n    cyclomatic_complexity AS Complexity\nFROM node\nWHERE git_total_commits > 5\nORDER BY cyclomatic_complexity DESC,avec_stability ASC\nLIMIT 1000;"
    }
   ]
  },
  {
   "title": "Developer Pains",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "targets": [
    {
     "mode": "raw",
     "rateFunctions": [ "count" ],
     "surql": "SELECT \navec_stability AS Stability,\navec_friction AS Friction,\narray::last(string::split(file_path, \"/\")) as FileName,\ngit_avg_days_between_changes AS AvgDaysBetweenChange,\ngit_contributors AS Contributors,\ngit_created AS DateCreated\nFROM node\nWHERE avec_friction > 0.3\nORDER BY avec_friction DESC\nLIMIT 10;"
    }
   ]
  }
 ]
}